# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2

      # Runs a single command using the runners shell
      - name: install PyInstaller
        run: pip install pyinstaller

      # Runs a set of commands using the runners shell
      - name: package the ExE
        run: pyinstaller main.py --onefile
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
            name: main.exe
            path: dist/main.exe

